# Site settings

title: Dev Curriculum | Simple and fast curriculum generator for developers # put your portfolio title
description: The fastest and simplest way to make a developer curriculum # put your description for your portfolio
baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Wendell Adriel
author-title: Full Stack Developer
gravatar: d36a082aacb53b6f76869748fb4b81d4
email: wendelladriel.ti@gmail.com
twitter: wendell_adriel
github: WendellAdriel
googleplus: +WendellAdriel
facebook: wendell.adriel.7
linkedin: wendelladrielti/en
bio: "Brazilian developer. Game, music and technology lover.
      I graduated in Systems Analysis and Development. I'm a Zend Certified PHP Engineer and Scrum Fundamentals Certified. I love to study and learn new skills,
      exchange work and study experience with people around me and share my knowledge with the ones that want it. I work with Web Development since 2009 and with
      Mobile Development since 2015 as Freelancer and in some Brazilian companies too.
      I'm the creator of CodeShare, a free portal with articles, videos, etc, about Software Development. The purpose of this project is to help people who want
      to learn about Software Development and start their careers in IT area and to help people that already work with Software Development to improve their
      technical knowledge to get better job opportunities.
      I like to work with both: Front-End and Back-End development. I work with many languages, frameworks and technologies."

# Skills

# You can customise the skill level name, for my use I'll use five differents levels:
# Studying: You know the basics of the skill and is studying it to get better
# Padawan: You know a little more than the basics and is comfortable to work with it
# Work with: You know how to handle the skill and how to properly use it in a real project
# Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# Jedi: You master the skill, know how and when to use and when not use it
front-end:
  - name: HTML 5
    level: Specialist
  - name: CSS 3
    level: Specialist
  - name: JavaScript
    level: Specialist

back-end:
  - name: PHP
    level: Jedi
  - name: Node
    level: Work with
  - name: Ruby
    level: Padawan

mobile:
  - name: Android
    level: Studying
  - name: Ionic
    level: Specialist
  - name: NativeScript
    level: Work with

db:
  - name: MySQL
    level: Specialist
  - name: PostgreSQL
    level: Work with
  - name: MongoDB
    level: Specialist

devops:
  - name: Docker
    level: Work with
  - name: Vagrant
    level: Work with
  - name: Jenkins
    level: Studying

methodologies:
  - name: Agile Methodologies
    level: Work with
  - name: Scrum
    level: Specialist
  - name: RUP
    level: Work with

others:
  - name: Git
    level: Specialist
  - name: Web Services
    level: Specialist
  - name: REST
    level: Specialist

# Navigation menu
links:
  - title: Bio
    section: bio
  - title: Front-end
    section: front-end
  - title: Back-end
    section: back-end
  - title: Mobile
    section: mobile
  - title: Database
    section: db
  - title: DevOps
    section: devops
  - title: Methodologies
    section: methodologies
  - title: Other Skills
    section: others
  - title: Contact
    section: contact

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap, bourbon, breakpoint]
